### ISSUE TITLE
New functional requirements

### ISSUE THREAD

**Issue by ghost** [divyavanmahajan/smokeping#2]
First of all thank you for creating such a user-friendly project so that I can quickly deploy my services,But for the sake of privacy and security, I have a requirement in the use process:Added web login authentication and allowed specific ip addresses to log in without a password (Slave).My English is not good, I communicate through translation software, please forgive me

**Comment by divyavanmahajan** [comment]
Hi,
I am no longer actively maintaining this project.
Regards

**Comment by ghost** [comment]
Thank you for your reply. I understand
